export const movies = [
  {
    title: "Inception",
    overview: "A thief who steals corporate secrets through dream-sharing technology.",
    description: "A detailed exploration of dreams within dreams, starring Leonardo DiCaprio.",
    director: "Christopher Nolan",
    screenplay: "Christopher Nolan",
    pgAge: "PG-13",
    genre: ["Action", "Sci-Fi", "Thriller"],
    releaseYear: 2010,
    rating: { average: 8.8, count: 25000 },
    price: 12.99,
    discountPrice: 9.99,
    quantity: 50,
    coverImage:
      "https://res.cloudinary.com/drmwwgsnu/image/upload/v1759813985/inception_kys1ff.webp",
    featured: true,
    comingSoon: false,
    languages: ["English", "French", "Japanese"],
  },
  {
    title: "Interstellar",
    overview: "A journey through space and time to save humanity’s future.",
    description: "Starring Matthew McConaughey, exploring love, time, and space.",
    director: "Christopher Nolan",
    screenplay: "Jonathan Nolan, Christopher Nolan",
    pgAge: "PG-13",
    genre: ["Adventure", "Sci-Fi", "Drama"],
    releaseYear: 2014,
    rating: { average: 8.6, count: 22000 },
    price: 14.99,
    discountPrice: 12.49,
    quantity: 40,
    coverImage:
      "https://res.cloudinary.com/drmwwgsnu/image/upload/v1759813985/interstellar_tecrwh.webp",
    featured: true,
    comingSoon: false,
    languages: ["English"],
  },
  {
    title: "The Dark Knight",
    overview: "Batman faces his greatest enemy — the Joker — in a battle for Gotham’s soul.",
    description: "Heath Ledger delivers a legendary performance as the Joker.",
    director: "Christopher Nolan",
    screenplay: "Jonathan Nolan, Christopher Nolan",
    pgAge: "PG-13",
    genre: ["Action", "Crime", "Drama"],
    releaseYear: 2008,
    rating: { average: 9.0, count: 30000 },
    price: 10.99,
    discountPrice: null,
    quantity: 60,
    coverImage:
      "https://res.cloudinary.com/drmwwgsnu/image/upload/v1759813985/thedarkknight_v9krjm.webp",
    featured: false,
    comingSoon: false,
    languages: ["English"],
  },
  {
    title: "Avengers: Endgame",
    overview: "The Avengers unite for one final stand against Thanos.",
    description: "Epic conclusion to the Infinity Saga with all Marvel heroes together.",
    director: "Anthony Russo, Joe Russo",
    screenplay: "Christopher Markus, Stephen McFeely",
    pgAge: "PG-13",
    genre: ["Action", "Adventure", "Fantasy"],
    releaseYear: 2019,
    rating: { average: 8.4, count: 18000 },
    price: 15.99,
    discountPrice: 13.99,
    quantity: 70,
    coverImage:
      "https://res.cloudinary.com/drmwwgsnu/image/upload/v1759813985/avengersendgame_musy42.webp",
    featured: true,
    comingSoon: false,
    languages: ["English", "Hindi"],
  },
  {
    title: "The Matrix",
    overview: "A hacker discovers reality is a simulation controlled by machines.",
    description: "Keanu Reeves stars in this revolutionary sci-fi action film.",
    director: "Lana Wachowski, Lilly Wachowski",
    screenplay: "Lana Wachowski, Lilly Wachowski",
    pgAge: "R",
    genre: ["Action", "Sci-Fi"],
    releaseYear: 1999,
    rating: { average: 8.7, count: 27000 },
    price: 9.99,
    discountPrice: 7.99,
    quantity: 30,
    coverImage:
      "https://res.cloudinary.com/drmwwgsnu/image/upload/v1759813985/matrix_jx5gtr.webp",
    featured: false,
    comingSoon: false,
    languages: ["English"],
  },
  {
    title: "Dune: Part Two",
    overview: "Paul Atreides unites the Fremen to wage war against House Harkonnen.",
    description: "Epic continuation of Denis Villeneuve’s adaptation of Dune.",
    director: "Denis Villeneuve",
    screenplay: "Jon Spaihts, Denis Villeneuve, Eric Roth",
    pgAge: "PG-13",
    genre: ["Adventure", "Sci-Fi"],
    releaseYear: 2024,
    rating: { average: 0, count: 0 },
    price: 16.99,
    discountPrice: null,
    quantity: 0,
    coverImage:
      "https://res.cloudinary.com/drmwwgsnu/image/upload/v1759814986/duneparttwo_hcojbh.webp",
    featured: true,
    comingSoon: true,
    languages: ["English"],
  },
];
